In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from sklearn.linear_model import LinearRegression

In [5]:
df=pd.read_csv(r"C:\Users\adith\OneDrive\Desktop\Adithya\My Projects\Linear Reg\Advertising.csv")
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [6]:
df.corr()  # Correlation to check more than one feature dependent to obtain optimal solution

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [7]:
x=df[['TV','Radio']].values
y=df['Sales'].values.reshape(-1,1)
x

array([[230.1,  37.8],
       [ 44.5,  39.3],
       [ 17.2,  45.9],
       [151.5,  41.3],
       [180.8,  10.8],
       [  8.7,  48.9],
       [ 57.5,  32.8],
       [120.2,  19.6],
       [  8.6,   2.1],
       [199.8,   2.6],
       [ 66.1,   5.8],
       [214.7,  24. ],
       [ 23.8,  35.1],
       [ 97.5,   7.6],
       [204.1,  32.9],
       [195.4,  47.7],
       [ 67.8,  36.6],
       [281.4,  39.6],
       [ 69.2,  20.5],
       [147.3,  23.9],
       [218.4,  27.7],
       [237.4,   5.1],
       [ 13.2,  15.9],
       [228.3,  16.9],
       [ 62.3,  12.6],
       [262.9,   3.5],
       [142.9,  29.3],
       [240.1,  16.7],
       [248.8,  27.1],
       [ 70.6,  16. ],
       [292.9,  28.3],
       [112.9,  17.4],
       [ 97.2,   1.5],
       [265.6,  20. ],
       [ 95.7,   1.4],
       [290.7,   4.1],
       [266.9,  43.8],
       [ 74.7,  49.4],
       [ 43.1,  26.7],
       [228. ,  37.7],
       [202.5,  22.3],
       [177. ,  33.4],
       [293.6,  27.7],
       [206.9,   8.4],
       [ 25.1,  25.7],
       [175.1,  22.5],
       [ 89.7,   9.9],
       [239.9,  41.5],
       [227.2,  15.8],
       [ 66.9,  11.7],
       [199.8,   3.1],
       [100.4,   9.6],
       [216.4,  41.7],
       [182.6,  46.2],
       [262.7,  28.8],
       [198.9,  49.4],
       [  7.3,  28.1],
       [136.2,  19.2],
       [210.8,  49.6],
       [210.7,  29.5],
       [ 53.5,   2. ],
       [261.3,  42.7],
       [239.3,  15.5],
       [102.7,  29.6],
       [131.1,  42.8],
       [ 69. ,   9.3],
       [ 31.5,  24.6],
       [139.3,  14.5],
       [237.4,  27.5],
       [216.8,  43.9],
       [199.1,  30.6],
       [109.8,  14.3],
       [ 26.8,  33. ],
       [129.4,   5.7],
       [213.4,  24.6],
       [ 16.9,  43.7],
       [ 27.5,   1.6],
       [120.5,  28.5],
       [  5.4,  29.9],
       [116. ,   7.7],
       [ 76.4,  26.7],
       [239.8,   4.1],
       [ 75.3,  20.3],
       [ 68.4,  44.5],
       [213.5,  43. ],
       [193.2,  18.4],
       [ 76.3,  27.5],
       [110.7,  40.6],
       [ 88.3,  25.5],
       [109.8,  47.8],
       [134.3,   4.9],
       [ 28.6,   1.5],
       [217.7,  33.5],
       [250.9,  36.5],
       [107.4,  14. ],
       [163.3,  31.6],
       [197.6,   3.5],
       [184.9,  21. ],
       [289.7,  42.3],
       [135.2,  41.7],
       [222.4,   4.3],
       [296.4,  36.3],
       [280.2,  10.1],
       [187.9,  17.2],
       [238.2,  34.3],
       [137.9,  46.4],
       [ 25. ,  11. ],
       [ 90.4,   0.3],
       [ 13.1,   0.4],
       [255.4,  26.9],
       [225.8,   8.2],
       [241.7,  38. ],
       [175.7,  15.4],
       [209.6,  20.6],
       [ 78.2,  46.8],
       [ 75.1,  35. ],
       [139.2,  14.3],
       [ 76.4,   0.8],
       [125.7,  36.9],
       [ 19.4,  16. ],
       [141.3,  26.8],
       [ 18.8,  21.7],
       [224. ,   2.4],
       [123.1,  34.6],
       [229.5,  32.3],
       [ 87.2,  11.8],
       [  7.8,  38.9],
       [ 80.2,   0. ],
       [220.3,  49. ],
       [ 59.6,  12. ],
       [  0.7,  39.6],
       [265.2,   2.9],
       [  8.4,  27.2],
       [219.8,  33.5],
       [ 36.9,  38.6],
       [ 48.3,  47. ],
       [ 25.6,  39. ],
       [273.7,  28.9],
       [ 43. ,  25.9],
       [184.9,  43.9],
       [ 73.4,  17. ],
       [193.7,  35.4],
       [220.5,  33.2],
       [104.6,   5.7],
       [ 96.2,  14.8],
       [140.3,   1.9],
       [240.1,   7.3],
       [243.2,  49. ],
       [ 38. ,  40.3],
       [ 44.7,  25.8],
       [280.7,  13.9],
       [121. ,   8.4],
       [197.6,  23.3],
       [171.3,  39.7],
       [187.8,  21.1],
       [  4.1,  11.6],
       [ 93.9,  43.5],
       [149.8,   1.3],
       [ 11.7,  36.9],
       [131.7,  18.4],
       [172.5,  18.1],
       [ 85.7,  35.8],
       [188.4,  18.1],
       [163.5,  36.8],
       [117.2,  14.7],
       [234.5,   3.4],
       [ 17.9,  37.6],
       [206.8,   5.2],
       [215.4,  23.6],
       [284.3,  10.6],
       [ 50. ,  11.6],
       [164.5,  20.9],
       [ 19.6,  20.1],
       [168.4,   7.1],
       [222.4,   3.4],
       [276.9,  48.9],
       [248.4,  30.2],
       [170.2,   7.8],
       [276.7,   2.3],
       [165.6,  10. ],
       [156.6,   2.6],
       [218.5,   5.4],
       [ 56.2,   5.7],
       [287.6,  43. ],
       [253.8,  21.3],
       [205. ,  45.1],
       [139.5,   2.1],
       [191.1,  28.7],
       [286. ,  13.9],
       [ 18.7,  12.1],
       [ 39.5,  41.1],
       [ 75.5,  10.8],
       [ 17.2,   4.1],
       [166.8,  42. ],
       [149.7,  35.6],
       [ 38.2,   3.7],
       [ 94.2,   4.9],
       [177. ,   9.3],
       [283.6,  42. ],
       [232.1,   8.6]])

In [8]:
lin=LinearRegression()
lin.fit(x,y)

LinearRegression()

In [11]:
Pred_y=lin.predict(x)
Pred_y

array([[21.21078412],
       [11.26581887],
       [10.48671441],
       [17.30620681],
       [15.63273693],
       [10.34542196],
       [11.27702065],
       [13.27626614],
       [ 5.32420713],
       [15.7884357 ],
       [ 8.85156828],
       [18.89326105],
       [ 9.68859218],
       [10.75417988],
       [19.26995575],
       [20.38243344],
       [12.24510831],
       [24.19693004],
       [10.59582626],
       [15.21268363],
       [19.49126811],
       [18.10365306],
       [ 7.05368143],
       [18.87282745],
       [ 9.37344932],
       [19.32062224],
       [15.55185089],
       [19.49389028],
       [21.08221178],
       [10.18976923],
       [23.61202043],
       [12.64300467],
       [10.0840803 ],
       [21.23601486],
       [ 9.99168941],
       [20.89860809],
       [23.85755331],
       [13.99264065],
       [ 9.83919073],
       [21.08572385],
       [18.04678695],
       [17.8479762 ],
       [23.58582996],
       [16.79663584],
       [ 8.75193486],
       [16.57632034],
       [10.5759795 ],
       [22.14092985],
       [18.69504157],
       [ 9.52745742],
       [15.84202299],
       [11.12643101],
       [20.88281419],
       [19.52472489],
       [22.0212491 ],
       [20.75520158],
       [ 8.03996233],
       [14.10457969],
       [21.42457912],
       [19.26492534],
       [ 7.75824801],
       [23.4347471 ],
       [19.32172162],
       [13.39515504],
       [16.35620987],
       [ 9.38458127],
       [ 8.98251618],
       [13.76965098],
       [20.50436345],
       [21.14037783],
       [18.75120943],
       [12.14197172],
       [ 9.62687247],
       [12.28747004],
       [18.88678214],
       [10.23459567],
       [ 6.2997052 ],
       [14.24645452],
       [ 8.12942354],
       [11.77220311],
       [11.65234112],
       [18.12715599],
       [10.90653001],
       [13.1244568 ],
       [20.86423915],
       [17.12243079],
       [11.73263588],
       [15.00966701],
       [12.17167427],
       [15.73231986],
       [12.46853029],
       [ 6.3488816 ],
       [20.07476636],
       [22.20399557],
       [11.97914185],
       [16.90911121],
       [15.7651051 ],
       [16.9491583 ],
       [24.93822776],
       [16.46155858],
       [17.20117899],
       [24.65998836],
       [20.96994143],
       [16.70524181],
       [21.27670971],
       [17.11229126],
       [ 7.17102377],
       [ 9.58521789],
       [ 5.38703068],
       [21.42014   ],
       [17.80428628],
       [21.86382698],
       [15.84805026],
       [18.2511778 ],
       [13.90455813],
       [12.47110641],
       [13.74277117],
       [ 8.87651972],
       [15.42985551],
       [ 7.40198244],
       [15.19679613],
       [ 7.98020812],
       [17.08466564],
       [15.0417867 ],
       [20.58865461],
       [10.64348878],
       [ 9.22467218],
       [ 8.99768611],
       [21.87753951],
       [ 9.16213238],
       [ 8.91310676],
       [19.38155011],
       [ 8.00339907],
       [20.18910917],
       [10.77698457],
       [12.29796912],
       [10.20458114],
       [22.63090513],
       [ 9.74800617],
       [19.40345598],
       [10.44940089],
       [18.97162298],
       [20.19507107],
       [10.93713581],
       [11.45505314],
       [12.47370034],
       [18.48644931],
       [23.12442071],
       [11.0190752 ],
       [ 9.82985195],
       [21.40442928],
       [12.11947011],
       [17.88716162],
       [18.21281692],
       [17.11777774],
       [ 6.09734523],
       [14.40573073],
       [12.92666072],
       [ 9.22267399],
       [13.7738197 ],
       [15.96318493],
       [13.13400505],
       [16.82892341],
       [17.47730877],
       [12.58776386],
       [17.7635543 ],
       [ 9.63527974],
       [16.44823231],
       [18.88850549],
       [21.24676946],
       [ 8.59655253],
       [15.82768205],
       [ 7.85228798],
       [14.56102391],
       [17.10472187],
       [24.94863323],
       [21.39267336],
       [14.73405424],
       [19.94340841],
       [14.71937307],
       [13.4362406 ],
       [17.10672007],
       [ 8.30180611],
       [24.89890714],
       [20.73284407],
       [20.62648958],
       [12.45157609],
       [18.11198606],
       [21.69300877],
       [ 6.94588734],
       [11.18648829],
       [ 9.89926137],
       [ 6.00681733],
       [18.21429811],
       [16.59730363],
       [ 7.10737568],
       [10.28512696],
       [15.26506903],
       [24.57393672],
       [18.19018456]])

In [12]:
from sklearn import metrics
print(metrics.mean_absolute_error(y,Pred_y))
print(metrics.mean_squared_error(y,Pred_y))

1.2367636706717362
2.7060525778834883